#!/bin/bash
#----------------------------------------------------
# Example SLURM job script to run MPI applications on 
# TACC's Maverick system.
#
# $Id: job.mpi 1580 2013-01-08 04:10:50Z karl $
#----------------------------------------------------

#SBATCH -J VideoLT              # Job name
#SBATCH -o myjob.%j.out       # Name of stdout output file (%j expands to jobId)
#SBATCH -p normal                # Queue name
#SBATCH -N 1                  # Total number of nodes requested (20 cores/node)
#SBATCH -n 1                 # Total number of mpi tasks requested
#SBATCH -t 48:00:00           # Run time (hh:mm:ss) - 1.5 hours

#SBATCH -A Traffic-Camera-Video      # <-- Allocation name to charge job against

# Launch the MPI executable named "a.out"

#ln -s /work/00410/huang/maverick/yolo/latest_yolo/darknet_dbg_0/cfg .
#ln -s /work/00410/huang/maverick/yolo/latest_yolo/darknet_dbg_0/data .
#ln -s /work/00410/huang/maverick/yolo/yolo.weights .
#module load cuda cudnn
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/work/00410/huang/stampede2/tools/ffmpeg-3.3/lib:/work/00410/huang/stampede2/tools/opencv3.3.0/lib
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/work/00410/huang/maverick/yolo/ffmpeg-3.3_build/lib


#../run/run.sh /work/00791/xwj/CTR/videos/July/0720 /work/00791/xwj/CTR/videos/July/out 1 4
./run.sh $1 $2 $3 $4 

#label_exe=/work/00410/huang/soda/lable_and_track/darknet/label_gpu
#track_exe=/work/00410/huang/soda/lable_and_track/darknet/tracking
#
#for fn in *.mp4; do
#  dir=${fn%.*}
#  echo $dir
#  mkdir $dir
#  mv $fn $dir
#  cd $dir
#  ln -s /work/00410/huang/maverick/yolo/latest_yolo/darknet_dbg_0/cfg .
#  ln -s /work/00410/huang/maverick/yolo/latest_yolo/darknet_dbg_0/data .
#  ln -s /work/00410/huang/maverick/yolo/yolo.weights 
#
#date -s
#echo "$label_exe $fn 1"
#$label_exe $fn 1 >> run.log 2>&1
#
#echo "$track_exe $fn yolo.log"
#$track_exe $fn yolo.log >>run.log 2>&1
#
#cd ..
#done



